language: java
sudo: false
install: true
addons:
  sonarqube:
    token:
      secure: r5KhIDmLmv0/ZiOS3llLd3Feh1L/UKAgXZAy1RrNdxIFJoAkRhdDyFkset0l1jnnesg947+crDm3/wZhji1ZnMlYsQ69ZqO30eW8CuiaOCxO3KKprop2/2by4WvunUbmJYX9xBar/Kpp7DesKgKhg9JWiqNQ2da6WEKrG6APNKwFOEqsK2qnsQ/ra8n0SvcgzzpPtAlFe8m3XstO9WkL+SnS0q+vD2tg6sIrRT2B6m3xSzzOk1nn//otvCiMPcDTmLQLoErqV57nkRfk+FTUBFZZ5QcsBR8qiArUunrkZqYVkXUVftlmudTvxfctP3sxxRCrifNJBxQ1Ylh+KkbNfKdzsZ1mDNgCd307pF1IU/M2HxqacLsS9/dTxUQS865Sq+md8K+lLxqwXuQSjcEpL/KuS9qKz5bShKwTnZAHbiXf1fuz7W7x2H5YfBcZMPFYmi9fJhB0H2xrRkBddyziOcvMuZSjmCRYvCUewAh9eZ4jbdAdGxuONZC4qkx+OfmEIWPh4Mgmw3lF9oJSns4hiiZD54T7OL+cZN+PFvb/726h1397LsHSSGGdfPeRV9C4edLhlDEPyg84taPoHaSh+0tZvv7OA96u0J/jdtVQey+k1umrfLec6REnKtrUO0NJNP8XfxGSS4EbbXDfOlertKpyU+CpECkZDoFRclKfXuo=
jdk:
- oraclejdk8
script:
- ./build.sh
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
env:
  global:
  - secure: B60cOwfC1yPqNAkOLzdQhH7Idf3SflBBb7nwu3hdgY4/6KVP/YDoSp06b+j4i1kHiKDsQivy1iEBGMsbAC33huwmKVufiY952ixNPMmBz/YD4UN6prxgeEO+NcXLXSUVFwppuq71VRCbcggNj3kHGDRvsx9pHXYFnx9Jli4ppAOA6Z0QrnINb2ob1ons3sx1T205NNBBRw87anEo71EtXtw8s3E7DcsPXZPR/7So6AfIs8cuaOtw0WXjJT+XKgMJKfOVjZiVHU6t3frbMZZgSbPMUeVnQ939JC646trEJBrdTTA+1d64DAksWjmmFSBWCBr1cHjB3kR3Jt5Yz0tSN55DZLXmV2ve4TG+firXN85EsmPFbEMaU12Vgjl51KavGlEf9+OSNv5LCjMBrmp+F9tv2jBqW36KVH9OoxVU89N9zELjgxJX9ZNfahvpd1DgGUR3ElD1AEI0MA0OefKl+oWrQmbmLetLEgvoOV4DqXFJ9UuuILjuhRmIM2cyjR6AiEW2Z1ZMns5vfP2c/hsj6rhYPdS6Upynl3IyD9BcABBaQXhpvVqz1Pv6cMeYEdVx/D8pgiQyETBqDyEO1nXzwWoHBAqf32+Qc/FCP9JFpIjRtdFV+Hgj6hKD2HWZU7fQCDXfessTTrlmZ/5HKXPA3sAXW7bN4j5wcXJNNYQBCXQ=
  - secure: ooAZmNOiI3cL0GmEFPeQVX+S74i77qxi1GrrZ3mfFdh0ItaJv0mbMsWbwimyUl/ZwXQy6H9NJYm0XrE6ukzbmLF9AsGVNBzdRbox7SgPuped/iOqjfUvEotPlIXVXyRZB4JxcBRLb2QWxt+E/HRnP1qooXbOjO/Haeon2ma4NsTizC+AvUUj60pikjPZgBzBkDBUN3w5wUD5jU15ziIgRKgyh1WjD6oLs7VOebvit7gGTHQD7g3BhsvJwvvPRofYWAuL73jq9tgtjZKaat3AA161668kTvWzR2jWHLiK4d/1XNSPTTkSQfw33Z44AglEXzwc/E6lwKC4g+ZrlCqQJSG3dVostQ+PCitkgsvgwiWXsTf7qwxrdV+jWu67Aog3QB9tJBA+9pS1QgTgNS4YcISSS3NhCBspCWB/znSH2fBnTzyxmvWkHtYRwZg4Nj0kaMhGGF576tfJ7NHzfBQfslYWHJRwsjeK8ravvKXa0yIZHfGIWno/5LA8v3KbLGT/nN0KIMbqCY7or6QOwl6+IukgMkVYec9/tneMr4j19dvRaJt+BVtKZrMk08INgzKScqAdB9UqfrMYnMlEAh/unlwtp7lVB8LJXkiFg8fn5C4iKoN1icSw+8qk9Qq1w+vAaLM05sNejTEGjpjbAdcTjQsp4a459ayV+4cPBp0cVnE=
